safe: true
plugins:
  - jekyll-feed
theme: minima
title: JupyterLab News
description: Subscribe to get news about JupyterLab.
baseurl: /assets
exclude:
  - src
  - README.md
  # Locally installed dependencies in CI test job
  - vendor/
feed:
  posts_limit: 1
